title: Julia Finite Element Community Conference
description: Vrije Universiteit Amsterdam - 26-27 March 2026
baseurl: Julia4PDEs-2026/
url: https://galerkintoolkit.github.io/

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: Robin Richardson, Francesc Verdugo
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
